-- Supabase SQL Editor에서 한 번 실행하세요.

-- deprecated: 더 이상 백엔드에서 사용하지 않음 (member_resume/member_skill로 대체됨)
create table if not exists public.resume (
  id bigint generated by default as identity primary key,
  filename text not null default '',
  raw_text text not null default '',
  uploaded_at timestamptz not null default now()
);

create table if not exists public.match_analysis (
  id                    bigserial primary key,
  resume_id             bigint not null references public.member_resume(id) on delete cascade,
  role_id               bigint not null references public.posting_role(id) on delete cascade,
  ai_match_score        int,
  score_reason          text,
  matched_points        jsonb default '[]'::jsonb,
  gap_points            jsonb default '[]'::jsonb,
  summary               text,
  recommended_emphasis  jsonb default '[]'::jsonb,
  created_at            timestamptz default now(),
  unique (resume_id, role_id)
);

create index if not exists idx_match_analysis_lookup
  on public.match_analysis (resume_id, role_id);

-- application.match_score는 이제 LLM 기반 추론 점수를 저장한다 (SQL 완전일치 스코어링 폐기).
alter table public.application
  add column if not exists match_reason text;

-- 이벤트 로깅 파이프라인: 조회/클릭/서비스 이용 이벤트를 단일 와이드 테이블 + JSONB로 수집.
-- duration_ms / max_scroll_depth_pct는 *_view 이벤트가 만든 행을 이탈 시점에 UPDATE해서 채운다.
create table if not exists public.event_log (
  id                   bigint generated by default as identity primary key,
  event_name           text not null,
  anonymous_id         text not null,
  session_id           text not null,
  posting_id           bigint references public.job_posting(id) on delete set null,
  role_id              bigint references public.posting_role(id) on delete set null,
  resume_id            bigint references public.member_resume(id) on delete set null,
  path                 text,
  properties           jsonb not null default '{}'::jsonb,
  duration_ms          integer,
  max_scroll_depth_pct smallint,
  referrer             text,
  user_agent           text,
  created_at           timestamptz not null default now()
);

create index if not exists idx_event_log_event_name on public.event_log (event_name);
create index if not exists idx_event_log_created_at on public.event_log (created_at);
create index if not exists idx_event_log_session_id on public.event_log (session_id);
create index if not exists idx_event_log_posting_id on public.event_log (posting_id) where posting_id is not null;
create index if not exists idx_event_log_duration on public.event_log (duration_ms) where duration_ms is not null;
