-- Supabase SQL Editor에서 한 번 실행하세요.

-- deprecated: 더 이상 백엔드에서 사용하지 않음 (member_resume/member_skill로 대체됨)
create table if not exists public.resume (
  id bigint generated by default as identity primary key,
  filename text not null default '',
  raw_text text not null default '',
  uploaded_at timestamptz not null default now()
);

create table if not exists public.match_analysis (
  id                    bigserial primary key,
  resume_id             bigint not null references public.member_resume(id) on delete cascade,
  role_id               bigint not null references public.posting_role(id) on delete cascade,
  ai_match_score        int,
  score_reason          text,
  matched_points        jsonb default '[]'::jsonb,
  gap_points            jsonb default '[]'::jsonb,
  summary               text,
  recommended_emphasis  jsonb default '[]'::jsonb,
  created_at            timestamptz default now(),
  unique (resume_id, role_id)
);

create index if not exists idx_match_analysis_lookup
  on public.match_analysis (resume_id, role_id);
