-- Supabase SQL Editor에서 한 번 실행하세요.

alter table public.job_posting
  add column if not exists company text not null default '',
  add column if not exists job_type text not null default '',
  add column if not exists industry text not null default '',
  add column if not exists deadline date,
  add column if not exists linkareer_url text,
  add column if not exists apply_url text,
  add column if not exists is_image_based boolean not null default false,
  add column if not exists raw_text text not null default '',
  add column if not exists collected_at timestamptz not null default now(),
  add column if not exists image_urls jsonb default '[]'::jsonb;

create unique index if not exists job_posting_linkareer_url_key
  on public.job_posting (linkareer_url);

create table if not exists public.submission_requirement (
  id bigint generated by default as identity primary key,
  posting_id bigint not null references public.job_posting(id) on delete cascade,
  type text not null check (type in ('자소서', '이력서', '포트폴리오', '기타')),
  is_required boolean not null default false,
  detail text
);

create table if not exists public.cover_letter_question (
  id bigint generated by default as identity primary key,
  posting_id bigint not null references public.job_posting(id) on delete cascade,
  role_id integer not null default 0,
  role_name text not null default '',
  question_text text not null,
  char_limit integer,
  question_order integer not null
);

alter table public.cover_letter_question
  add column if not exists role_id integer not null default 0,
  add column if not exists role_name text not null default '';

create index if not exists submission_requirement_posting_id_key
  on public.submission_requirement (posting_id);

create index if not exists cover_letter_question_posting_id_key
  on public.cover_letter_question (posting_id);